### ISSUE TITLE
How to start project in development mode?

### ISSUE THREAD

**Issue by ynejati** [collectionspace/cspace-input.js#8]
I'd like to start building components for the new UI. I don't recognize any commands to run a dev server under the script property in the package.json. How do you suggest we do this? Thanks!

**Comment by ray-lee** [comment]
For this project I've just been using Karma as a dev server. So I run `npm start`, click the DEBUG button in the browser that opens, and hang out in the debug runner tab. This runs the tests, and leaves the rendered components on the page so you can interact with them.

Normally I only run the tests for the component I'm working on, so something like:
```
npm start -- --file=test/specs/components/DateInput.spec.jsx
```
The downside of this approach is that that tab doesn't hot reload, so you have to manually reload to see changes. And if you write tests that only use shallow rendering, there won't be anything to see. I'm open to putting webpack dev server in there, if you think it would be useful.

**Comment by ynejati** [comment]
Yes, I see now. I ran npm start thinking that it would open up a new tab in my current browser window and not produce a new window of a size that is typical of a popup advertisement, hence overlooking this new window as it was covered up.  Thanks for clarifying. 

I see why you run only the tests for the component you're working on, it does take a while to run all of the tests. I have not used Karma before so I'll need to thoroughly read up more on the docs.

I've used Browser-Sync to test various browsers and mobile devices with my react projects which has been quite helpful https://browsersync.io/. 

It sounds to me that adding a webpack dev server would a good idea. What do you think?

**Comment by ray-lee** [comment]
Ah, that's interesting. It opens a big window for me. You're probably the first person other than me to seriously try to work with this stuff, so it might be a bit rocky. It does look like we can pass a window size, at least to Chrome: http://www.mattjmorrison.com/today-i-learned/2014/09/24/learned.html

Any chance you can put together a pull request to add webpack dev server? It looks like Browsersync covers a different use case than Sauce Labs, right? I'm open to having that in there as well.

**Comment by ynejati** [comment]
I wouldn't say seriously, not yet. I still have much to learn about node and webpack. Thanks for the reference, I see how simple it is to pass window size parameters in the karma conf file.  For me it opens in a 1050 x 560 window in the background. Maybe those are default settings? 

Yes, it appears you're right, Browsersync is not comparable to Karma in most regards. I'd love to be able to add webpack dev server with hot reload in addition to Browersync but I'm not confident in my abilities to do so. My experience does not go far beyond building components and passing props and states. I'll contact you next week to discuss possible tasks, possibly writing tests. 

Outside of adding a bit of documentation to the README about how to run this project, I believe this issue can be closed now.
